name: 'poetry'
description: 'Setup poetry'
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: true
    default: "1.1.4"
runs:
  using: "composite"
  steps:
    - run: |
        curl -sSL https://install.python-poetry.org | python3 - --yes --version ${{ inputs.poetry-version }}
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        source $HOME/.poetry/env
        poetry --version
      shell: bash
