name: 'poetry'
description: 'Setup poetry'
inputs:
  poetry-version:
    description: "The version of poetry to install"
    required: true
    default: "1.1.4"
runs:
  using: "composite"
  steps:
    - run: |
        wget https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        wget https://github.com/python-poetry/poetry/releases/download/${{ inputs.poetry-version }}/poetry-${{ inputs.poetry-version }}-linux.tar.gz
        python get-poetry.py --force -y --file=poetry-${{ inputs.poetry-version }}-linux.tar.gz
      shell: bash